# Generated by Django 2.2.10 on 2020-05-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.TextField(default='user', max_length=50, verbose_name='User role'),
        ),
    ]
