# Generated by Django 2.2.10 on 2020-05-22 22:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchangeRate', models.FloatField(default=0, verbose_name='exchangeRate')),
                ('changedRate', models.FloatField(default=0, verbose_name='changedRate')),
            ],
            options={
                'db_table': 'Exchange_Rate',
            },
        ),
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minerID', models.CharField(max_length=500, unique=True, verbose_name='miner_ID')),
                ('minedCoins', models.IntegerField(default=0, max_length=1000, verbose_name='mined_Coins')),
            ],
            options={
                'db_table': 'WC_LeaderBoard',
            },
        ),
        migrations.CreateModel(
            name='UserCoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocateWasteCoin', models.IntegerField(default=0, verbose_name='AllocatedWasteCoin')),
                ('minedCoins', models.IntegerField(default=0, verbose_name='minedCoins')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'db_table': 'User_Coins',
            },
        ),
    ]
