# Generated by Django 2.2.10 on 2020-04-29 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.IntegerField(verbose_name='OTP'),
        ),
    ]
