# Generated by Django 2.2.10 on 2020-05-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exchangerate_leaderboard_usercoins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='minedCoins',
            field=models.IntegerField(default=0, verbose_name='mined_Coins'),
        ),
    ]
