# Generated by Django 2.2.10 on 2020-05-04 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20200429_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_reset_code',
            field=models.TextField(default='', max_length=20, verbose_name='Reset Code'),
        ),
    ]
