# Generated by Django 2.2.10 on 2020-05-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_otp_otp_reset_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='otp_code',
            field=models.TextField(verbose_name='OTP'),
        ),
    ]
