# Generated by Django 2.2.10 on 2020-05-17 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20200513_0154'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
