# Generated by Django 2.2.10 on 2020-05-17 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_delete_otp'),
    ]

    operations = [
        migrations.CreateModel(
            name='otp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password_reset_code', models.TextField(default='', max_length=20, verbose_name='Reset Code')),
            ],
            options={
                'db_table': 'OTP_Code',
            },
        ),
    ]
