# Generated by Django 2.2.10 on 2020-05-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20200526_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrasactionhistory',
            name='transaction_id',
            field=models.IntegerField(default=0, unique=True, verbose_name='trans_id'),
        ),
    ]
