# Generated by Django 2.2.10 on 2020-05-26 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_usertrasactionhistory_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrasactionhistory',
            name='transaction_id',
            field=models.IntegerField(unique=True, verbose_name='trans_id'),
        ),
    ]
