# Generated by Django 2.2.10 on 2020-05-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20200526_1549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrasactionhistory',
            name='transaction_id',
            field=models.TextField(unique=True, verbose_name='trans_id'),
        ),
    ]
