# Generated by Django 2.2.10 on 2020-05-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20200526_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangerate',
            name='changedRate',
            field=models.FloatField(verbose_name='changedRate'),
        ),
        migrations.AlterField(
            model_name='exchangerate',
            name='exchangeRate',
            field=models.FloatField(verbose_name='exchangeRate'),
        ),
        migrations.AlterField(
            model_name='usertrasactionhistory',
            name='coin_mined',
            field=models.FloatField(verbose_name='Coinmined'),
        ),
    ]
