# Generated by Django 2.2.10 on 2020-05-27 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20200526_2246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoins',
            name='allocateWasteCoin',
            field=models.FloatField(verbose_name='AllocatedWasteCoin'),
        ),
        migrations.AlterField(
            model_name='usercoins',
            name='minedCoins',
            field=models.FloatField(verbose_name='minedCoins'),
        ),
    ]
