# Generated by Django 2.2.10 on 2020-05-28 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_delete_exchangerate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoins',
            name='allocateWasteCoin',
            field=models.FloatField(default=0, verbose_name='AllocatedWasteCoin'),
        ),
        migrations.AlterField(
            model_name='usercoins',
            name='minedCoins',
            field=models.FloatField(default=0, verbose_name='minedCoins'),
        ),
    ]
