# Generated by Django 2.2.10 on 2020-05-29 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20200528_0121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrasactionhistory',
            name='coin_mined',
        ),
        migrations.AddField(
            model_name='usertrasactionhistory',
            name='coin_mined_amount',
            field=models.FloatField(default=0, verbose_name='CoinminedAmount'),
        ),
    ]
