# Generated by Django 2.2.10 on 2020-06-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_auto_20200601_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercoins',
            name='minerID',
            field=models.CharField(max_length=500, unique=True, verbose_name='miner_ID'),
        ),
    ]
