# Generated by Django 2.2.10 on 2020-06-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_accountdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='otp_code',
            field=models.TextField(default='', max_length=20, verbose_name='OTP CODE'),
        ),
    ]
