# Generated by Django 2.2.10 on 2020-06-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_usertrasactionhistory_coin_allocated_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usercoins',
            old_name='allocateWasteCoin',
            new_name='unminedWasteCoin',
        ),
    ]
