# Generated by Django 2.2.10 on 2020-06-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_auto_20200607_1328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertrasactionhistory',
            old_name='coin_mined_amount',
            new_name='coin_unmined_amount',
        ),
    ]
