# Generated by Django 2.2.10 on 2020-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_auto_20200607_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrasactionhistory',
            name='coin_unmined_amount',
            field=models.FloatField(default=0, verbose_name='CoinunminedAmount'),
        ),
    ]
