# Generated by Django 2.2.10 on 2020-06-07 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_auto_20200607_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertrasactionhistory',
            old_name='coin_unmined_amount',
            new_name='coin_redeemed_amount',
        ),
        migrations.RemoveField(
            model_name='usercoins',
            name='unminedWasteCoin',
        ),
        migrations.AddField(
            model_name='usercoins',
            name='redeemedWasteCoin',
            field=models.FloatField(default=0, verbose_name='redeemedWasteCoin'),
        ),
    ]
