# Generated by Django 2.2.10 on 2020-06-07 18:47

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_auto_20200607_1534'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCoins',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agentCoins', models.FloatField(default=0, verbose_name='AllocatedCoins')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'db_table': 'Agent_Coins',
            },
        ),
    ]
