# Generated by Django 2.2.10 on 2020-06-07 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_usercoins_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercoins',
            name='balance',
        ),
    ]
