# Generated by Django 2.2.10 on 2020-06-07 22:29

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_remove_usercoins_balance'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='usertrasactionhistory',
            table='User_Transaction_History',
        ),
        migrations.CreateModel(
            name='AgentTransactionHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.TextField(unique=True, verbose_name='trans_id')),
                ('amount', models.FloatField(verbose_name='CoinAmount')),
                ('coin_allocated_to', models.TextField(default=0, verbose_name='Miner_ID')),
                ('transaction', models.TextField(max_length=10, verbose_name='Transactions')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.User')),
            ],
            options={
                'db_table': 'Agent_Transaction_History',
            },
        ),
    ]
