# Generated by Django 2.2.10 on 2020-06-07 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_auto_20200607_2229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrasactionhistory',
            name='coin_allocated_to',
        ),
    ]
