# Generated by Django 2.2.10 on 2020-06-08 21:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_remove_usertrasactionhistory_coin_allocated_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.TextField(verbose_name='Full_Name')),
                ('email', models.TextField(max_length=200, verbose_name='email')),
                ('phone_number', models.TextField(max_length=20, verbose_name='phone_number')),
                ('message', models.TextField(verbose_name='message')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'Contact Us',
            },
        ),
    ]
