# Generated by Django 2.2.10 on 2020-06-08 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='phone_number',
            field=models.TextField(default='', max_length=20, verbose_name='phone_number'),
        ),
    ]
