# Generated by Django 2.2.10 on 2020-07-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_auto_20200608_2139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_LGA',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_state',
        ),
    ]
