# Generated by Django 2.2.10 on 2020-07-05 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_auto_20200704_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_LGA',
            field=models.TextField(max_length=200, verbose_name='LGA'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_state',
            field=models.TextField(max_length=200, verbose_name='State'),
        ),
    ]
